version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "MuuEAbXMbkjGilGkCzKsZfL+xd/6q4fB8RkV9kFSImdkcpOwrjoxC5OhXwuO5y9oyzI1QWJLTtZPR/ndHW5CSRDolQat7ICo1c+DUeuosl9dDu7hvrsffKT3Rsu9M9MpFjxWTCj8gRx45jZgXOYBgQjTH89MhKwEj81FJyssKNI="
        - secure: "FeX9QosEth+7AxTbSOQe+0oyJaO6oPKKPCL0ErVDRGGCo9e3kVfUcnZ9CZyBtbwmwsrmC7AoE+6O/hJQ2QgGkG+EMY+qVuH+YGs4GGcSgdrF89ep+9RR/Hh3i1G4lfoA4uSjLjnfNVxnOLCpAttJlTd9mW5U2Gz0WtSNGKHJh3Q="
